### ISSUE TITLE
Add helpers to creates paths in 2dii's dropbox folder

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.utils#1]
Accessing the local Dropbox folder is problematic because...
- the path to the user's home directory (the default location of the Dropbox directory) is different per OS/user
- the name and location of the Dropbox directory can be modified from the default by the user
- a user can have a personal and a business Dropbox account installed simultaneously, which will change the default names of Dropbox directories

Dropbox uses a hidden config file to track the location of its directory that has a fixed location on each operating system [according to the documentation](https://help.dropbox.com/installs-integrations/desktop/locate-dropbox-folder).

Additional considerations are...
- (apparently) Dropbox [localizes the key names of its config file](https://www.dropboxforum.com/t5/Installs-integrations/Keys-in-info-json-are-localized/td-p/7101) (!?!?!)
- some special characters, like the '°' in '2°', can be encoded differently even in UTF-8, so if you're trying to match file paths that might contain these, you should probably test them for [canonical equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence)

I propose the following function to easily, but safely determine the path to the business Dropbox directory on (hopefully) any system. I added a few possible localizations of 'business' to work around the possibly localized keys, but I'm honestly just guessing what they may be and what may be likely to occur inside this organization (English, German, French, Spanish).

I can't (easily) test this on Windows, nor on systems with non-English locales, nor on systems with personal and business Dropbox accounts installed, so I'd be happy to get feedback and suggestions.

Side note: `path.expand("~")` is probably the safest cross platform way of determining the user's home directory.

```r
# based on:
# https://help.dropbox.com/installs-integrations/desktop/locate-dropbox-folder

# additional considerations
# https://www.dropboxforum.com/t5/Installs-integrations/Keys-in-info-json-are-localized/td-p/7101
# https://www.dropboxforum.com/t5/Discuss-Developer-API/Problem-with-special-charachters-in-Company-name/m-p/318277#M351


dropbox_path <- 
  function(..., read_error = TRUE, write_error = TRUE, warn = TRUE) {
    if (!require('jsonlite', quietly = TRUE)) {
      stop('The jsonlite package is required to run this function.')
    }
    
    report_text <- '\n\nPlease consider reporting this error at: https://github.com/2DegreesInvesting/Reference'
    
    # determine the platform type and read the appropriate Dropbox info.json
    if (.Platform$OS.type == 'unix') {
      if (file.exists('~/.dropbox/info.json')) {
        dropbox_info <- jsonlite::read_json('~/.dropbox/info.json')
        
      } else {
        stop('File "~/.dropbox/info.json" could not be found on this system.', report_text)
      }
      
    } else if (.Platform$OS.type == 'window') {
      if (file.exists('%APPDATA%\\Dropbox\\info.json')) {
        dropbox_info <- jsonlite::read_json('%APPDATA%\\Dropbox\\info.json')
        
      } else if (file.exists('%LOCALAPPDATA%\\Dropbox\\info.json')) {
        dropbox_info <- jsonlite::read_json('%LOCALAPPDATA%\\Dropbox\\info.json')
        
      } else {
        stop('File "%APPDATA%\\Dropbox\\info.json" or "%LOCALAPPDATA%\\Dropbox\\info.json" could not be found on this system.', report_text)
      }
      
    } else {
      stop('.Platform$OS.type not understood on this system (should be either "unix" or "windows")', report_text)
    }
    
    
    # determine how the business account is named in the Dropbox info.json file
    
    # various localizations of "business" that Dropbox might use
    business_localizations <- c('business', 'unternehmen', 'empresa', 'compagnie')
    
    names_in_localizations <- names(dropbox_info) %in% business_localizations
    
    if (!any(names_in_localizations)) {
      stop('A Dropbox business account was not found in the Dropbox config file.', report_text)
    }
    
    # extract the business path from the Dropbox info.json
    business_account_id <- names(dropbox_info)[names_in_localizations][[1]]
    dropbox_path <- dropbox_info[[business_account_id]]$path
    
    # make sure it exists
    if (file.access(dropbox_path, mode = 0) != 0) {
      stop('The path defined in the Dropbox config file does not exist.', report_text)
    }
    
    
    # build path to optional subpath/s
    dropbox_path <- file.path(dropbox_path, ...)
    
    # make sure it exists
    if (file.access(dropbox_path, mode = 0) != 0) {
      stop('The path does not exist:\n', dropbox_path)
    }
    
    # warn if the user does not have read/write permission
    if (file.access(dropbox_path, mode = 4) != 0) {
      if (read_error) {
        stop('The path is not readable by the current user:\n', dropbox_path)
      } else if (warn) {
        warning('The path is not readable by the current user:\n', dropbox_path)
      }
    }
    
    if (file.access(dropbox_path, mode = 2) != 0) {
      if (write_error) {
        stop('The path is not writable by the current user:\n', dropbox_path)
      } else if (warn) {
        warning('The path is not writable by the current user:\n', dropbox_path)
      }
    }
    
    
    dropbox_path
  }
```

**Comment by cjyetman** [comment]
I thought there was a combining version of the UTF-8 degree symbol, but I was wrong, so the bit about canonical equivalence is irrelevant to that. There are a number of other characters, particularly superscript 'o' and superscript zero, that look a lot like the degree symbol and could easily be confused, but I don't know of any proper way of dealing with that possibility.

**Comment by maurolepore** [comment]
I'm renaming the issue to reflect the new direction this issue is going -- that of addressing @cjyetman's comments by bringing here some functions that exist elsewhere and then going from there.

**Comment by maurolepore** [comment]
See https://2degreesinvesting.github.io/r2dii.utils/reference/index.html

If needed we can reopen.

**Comment by cjyetman** [comment]
I finally got around to testing my proposed function above on a Windows virtual environment, and *surprise*, it doesn't work. Even though this issue is closed, I wanted to put a working version of it here to avoid any confusion if this were ever referred to in the future for some reason.

The following has been tested on at least one macOS and one virtual Windows machine, and it worked as expected on both (under the specific conditions of those two machines anyway)...
```
# based on:
# https://help.dropbox.com/installs-integrations/desktop/locate-dropbox-folder

# additional considerations
# https://www.dropboxforum.com/t5/Installs-integrations/Keys-in-info-json-are-localized/td-p/7101
# https://www.dropboxforum.com/t5/Discuss-Developer-API/Problem-with-special-charachters-in-Company-name/m-p/318277#M351


dropbox_path <- 
  function(..., read_error = TRUE, write_error = TRUE, warn = TRUE) {
    if (!require('jsonlite', quietly = TRUE)) {
      stop('The jsonlite package is required to run this function.')
    }
    
    report_text <- '\n\nPlease consider reporting this error at: https://github.com/2DegreesInvesting/Reference'
    
    # determine the platform type and read the appropriate Dropbox info.json
    if (.Platform$OS.type == 'unix') {
      if (file.exists('~/.dropbox/info.json')) {
        dropbox_info <- jsonlite::read_json('~/.dropbox/info.json')
        
      } else {
        stop('File "~/.dropbox/info.json" could not be found on this system.', report_text)
      }
      
    } else if (.Platform$OS.type == 'windows') {
      appdata_path <- file.path(Sys.getenv('APPDATA'), 'Dropbox\\info.json')
      localappdata_path <- file.path(Sys.getenv('LOCALAPPDATA'), 'Dropbox\\info.json')
      
      if (file.exists(appdata_path)) {
        dropbox_info <- jsonlite::read_json(appdata_path)
        
      } else if (file.exists(localappdata_path)) {
        dropbox_info <- jsonlite::read_json(localappdata_path)
        
      } else {
        stop('File "%APPDATA%\\Dropbox\\info.json" or "%LOCALAPPDATA%\\Dropbox\\info.json" could not be found on this system.', report_text)
      }
      
    } else {
      stop('.Platform$OS.type not understood on this system (should be either "unix" or "windows")', report_text)
    }
    
    
    # determine how the business account is named in the Dropbox info.json file
    
    # various localizations of "business" that Dropbox might use
    business_localizations <- c('business', 'unternehmen', 'empresa', 'compagnie')
    
    names_in_localizations <- names(dropbox_info) %in% business_localizations
    
    if (!any(names_in_localizations)) {
      stop('A Dropbox business account was not found in the Dropbox config file.', report_text)
    }
    
    # extract the business path from the Dropbox info.json
    business_account_id <- names(dropbox_info)[names_in_localizations][[1]]
    dropbox_path <- dropbox_info[[business_account_id]]$path
    
    # make sure it exists
    if (file.access(dropbox_path, mode = 0) != 0) {
      stop('The path defined in the Dropbox config file does not exist.', report_text)
    }
    
    
    # build path to optional subpath/s
    dropbox_path <- file.path(dropbox_path, ...)
    
    # make sure it exists
    if (file.access(dropbox_path, mode = 0) != 0) {
      stop('The path does not exist:\n', dropbox_path)
    }
    
    # warn if the user does not have read/write permission
    if (file.access(dropbox_path, mode = 4) != 0) {
      if (read_error) {
        stop('The path is not readable by the current user:\n', dropbox_path)
      } else if (warn) {
        warning('The path is not readable by the current user:\n', dropbox_path)
      }
    }
    
    if (file.access(dropbox_path, mode = 2) != 0) {
      if (write_error) {
        stop('The path is not writable by the current user:\n', dropbox_path)
      } else if (warn) {
        warning('The path is not writable by the current user:\n', dropbox_path)
      }
    }
    
    
    normalizePath(dropbox_path)
  }
```

**Comment by cjyetman** [comment]
I found one real world example (@looreen's machine) where the Dropbox folder is **not** named "Dropbox (2° Investing)", which is the general assumption that is made in much of 2dii's code... and that's precisely what this example code is intended to work around.

**Comment by maurolepore** [comment]
Interesting. 

What if we provided an option to set a custom Dropbox folder? It could be done once in the .Rprofile. That could save us from writing quite a bit of code.

``` r
library(rlang)
library(r2dii.utils)

path_dropbox_2dii <- function(...) {
  custom <- getOption("r2dii_dropbox")
  default <- fs::path_home(glue::glue("Dropbox (2{degrees()} Investing)"), ...)
  fs::path_home(custom %||% default, ...)
}

# Use default path
path_dropbox_2dii("path", "to", "somewhere")
#> C:/Users/Mauro/C:/Users/Mauro/Dropbox (2° Investing)/path/to/somewhere/path/to/somewhere

# Set custom path (maybe in .Rprofile?)
restore <- options(r2dii_dropbox = "Custom Dropbox folder")
path_dropbox_2dii("path", "to", "somewhere")
#> C:/Users/Mauro/Custom Dropbox folder/path/to/somewhere

options(restore)
```

<sup>Created on 2019-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cjyetman** [comment]
That's an excellent solution!

**Comment by cjyetman** [comment]
There's a bug in that code though. Should be...

```r
library(rlang)
library(r2dii.utils)

path_dropbox_2dii <- function(...) {
  custom <- getOption("r2dii_dropbox")
  default <- glue::glue("Dropbox (2{degrees()} Investing)")
  fs::path_home(custom %||% default, ...)
}

# Use default path
path_dropbox_2dii("path", "to", "somewhere")
```

so the home directory doesn't get duplicated when using default

**Comment by cjyetman** [comment]
and not to be difficult, but I would prefer to see some error checking in there, like test if the directory exists before returning it and stop with an error possibly suggesting to set the .Rprofile option if your Dropbox folder is not "Dropbox (2° Investing)"

**Comment by maurolepore** [comment]
> I would prefer to see some error checking in there, like test if the directory exists before returning it

Yeah, `path_r2dii_dropbox()` is very liberal because it is a really thin wrapper around `fs::path_home()`. For example, this is valid:

``` r
fs::path_home("path", "that", "does", "not", "exits")
#> C:/Users/Mauro/path/that/does/not/exits
```

While I support your the idea of throwing informative error messages, I like having a low level function and do error checking at higher levels. For example:

``` r
library(r2dii.utils)

dropbox_exists()
#> C:/Users/Mauro/Dropbox (2° Investing) 
#>                                  TRUE

withr::with_options(
  list(r2dii_dropbox = "A custom dropbox folder that does not exist"),
  
  if (!dropbox_exists()) {
    stop("Can't find ", getOption("r2dii_dropbox"), call. = FALSE)
  }
  
)
#> Error: Can't find A custom dropbox folder that does not exist
```

How about this? 

I could transform `path_2dii_dropbox()` into a more user-oriented function, that does error checking. And keep the current low level implementation as an internal bare-bones function, say, `path_2dii_dropbox_impl()`.

**Comment by cjyetman** [comment]
it's up to you... I just feel most end-users of this are not gonna pay attention to all these intricacies... they're just gonna use `path_r2dii_dropbox()` (if we're lucky to convince them on that) and assume it works... they'll likely never or rarely see the result of that function because it will probably get saved directly to an object in their environment, and then so many other things downstream will depend on that being correct... if we were certain that all functions downstream, if they failed because the path was wrong, would throw an informative error that makes it clear that the problem is that the Dropbox name is wrong, then checking it first probably isn't necessary.... but I fear there's enough ways for a non-existent path to be used without error, and that can end up substantially confusing things when there's a strong expectation that `path_r2dii_dropbox()` is simply correct, for instance...

```r
project_path <- path_dropbox_2dii("path", "to", "nowhere")

list.files(project_path)
# character(0)
```

**Comment by cjyetman** [comment]
I guess it's somewhat of a psychological thing... when I look at `path_r2dii_dropbox()`, I think "ok, this function is gonna sort this out for me because this is something potentially problematic for me to sort out by myself", and so, I have a very strong expectation that the function is going to do what is promised, which I interpret to be "figure out what the path to my Dropbox is and give it to me", so I'd be very surprised if it gave me something else, which it shouldn't normally do, but it will if the users Dropbox is named differently and they haven't yet set their options properly, or if somehow their options got mangled in an update or reinstall, or something like that.

**Comment by maurolepore** [comment]
Thanks @cjyetman, I build on your comment about what users expect from the name of the function. I added the new `find_dropbox_2dii()` which I think more clearly communicates that the user should expect it to return a path to an existing directory. `path_dropbox_2dii()` stayed the same. 

https://2degreesinvesting.github.io/r2dii.utils/reference/find_dropbox_2dii.html

``` r
library(r2dii.utils)

find_dropbox_2dii()
#> C:/Users/Mauro/Dropbox (2° Investing)

path_dropbox_2dii()
#> C:/Users/Mauro/Dropbox (2° Investing)


# Warns if Dropbox folder exists but not the path nested in it
dropbox_exists()
#> C:/Users/Mauro/Dropbox (2° Investing) 
#>                                  TRUE
find_dropbox_2dii("path", "to", "nowhere")
#> Warning: The output path doesn't exist:
#> 'C:/Users/Mauro/Dropbox (2° Investing)/path/to/nowhere'
#> Do you need to create it?
#> C:/Users/Mauro/Dropbox (2° Investing)/path/to/nowhere

# Doesn't care
path_dropbox_2dii("path", "to", "nowhere")
#> C:/Users/Mauro/Dropbox (2° Investing)/path/to/nowhere

restore <- options(r2dii_dropbox = "No Dropbox folder here")

# Errs if Dropbox folder doesn't exist
dropbox_exists()
#> C:/Users/Mauro/No Dropbox folder here 
#>                                 FALSE
try(
  find_dropbox_2dii("path", "to", "nowhere")
)
#> Error :   The path to 2dii's Dropbox folder must exist, but this path doesn't:
#>   'C:/Users/Mauro/No Dropbox folder here'
#>   Did you add your custom Dropbox folder in .Rprofile? Example:
#>   `options(r2dii_dropbox = 'Name of your 2dii's dropbox folder')`

# Doesn't care
path_dropbox_2dii("path", "to", "nowhere")
#> C:/Users/Mauro/No Dropbox folder here/path/to/nowhere

options(restore)
```

<sup>Created on 2019-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
As I read the warning/error I realize maybe I should write "the _directory_ doesn't exist" -- not the _path_.
